### ISSUE TITLE
Projekt-Check aus dem QGIS-Repo startet nicht fehlerfrei

### ISSUE THREAD

**Issue by jannefleischer** [projektcheck/ProjektCheck-QGIS#6]
Zwecks hosting-Übergabe teste ich gerade nochmal Projekt-Check und habe Probleme es zum Laufen zu bringen. Ich erhalte unten stehende Fehlermeldung.

Installiert ist QGIS via OSGeo4w-Installer auf Windows 10.
Sowohl auf 3.10.10 als auch in 3.14.irgendwas gibt es diesen Fehler. Beide mit frischem Nutzeraccount getestet.

Auch der current master-branch macht mir leider probleme. Außerdem wäre vernünftiges Taging hilfreich. Dann könnte ich mir vielleicht einen altes stable ziehen können, wenn es gerade noch/wieder work-in-progress ist.

```
Konnte Erweiterung 'projektcheck' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode

FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden. 
Traceback (most recent call last):
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python/plugins\projektcheck\__init__.py", line 36, in classFactory
    from .ProjektCheck import ProjektCheck
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python/plugins\projektcheck\ProjektCheck.py", line 32, in 
    from .main_widget import ProjektCheckControl
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python/plugins\projektcheck\main_widget.py", line 40, in 
    from projektcheck.domains.definitions.definitions import ProjectDefinitions
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python/plugins\projektcheck\domains\definitions\definitions.py", line 31, in 
    from projektcheck.base.tools import MapClickedTool
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python/plugins\projektcheck\base\tools.py", line 32, in 
    from typing import Union, List
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 784, in _import
    _import_paths[p] = _AddDllDirectory(p)
  File "C:/OSGEO4~3/apps/qgis-ltr/./python\qgis\utils.py", line 731, in _errcheck_zero
    raise ctypes.WinError(ctypes.get_last_error())
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden.


Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.10.10-A Coruña A Coruña, 8b051b9a43 

Python-Pfad:
C:/OSGEO4~3/apps/qgis-ltr/./python
C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python
C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python/plugins
C:/OSGEO4~3/apps/qgis-ltr/./python/plugins
C:\OSGEO4~3\apps\Python37
C:\OSGEO4~3\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~3\apps\Python37\DLLs
C:\OSGEO4~3\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~3\apps\Python37\lib\site-packages
C:\OSGEO4~3\apps\Python37\lib\site-packages\win32
C:\OSGEO4~3\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~3\apps\Python37\lib\site-packages\Pythonwin
C:\OSGeo4W64\apps\qgis\python
C:/Users/fleischer/AppData/Roaming/QGIS/QGIS3\profiles\fleischer_qgisLTR/python
```

**Comment by jannefleischer** [comment]
Ich nehme alles zurück! Der Fehler lag zwischen Tastatur und Stuhl (und ein bisschen in einer defekten OSGeo4w-Envirionment).
